### ISSUE TITLE
Compatibility issues with Embeddium... but worse?

### ISSUE THREAD

**Issue by hibleepbloop** [ThinkingStudios/textrues-embeddium-options#11]
Trying to run a modpack on forge using embeddium 0.3.21, it says that textrue's is incompatible, blah blah. But, when I try to remove textrue's options, it says:

"Mod embeddiumextras requires textrues_embeddium_options any;
Currently, textrues_embeddium_options is _not installed_."

Sooo... I just... can't run the modpack anymore? If I try and run it _with_ textrue's options, it breaks, but if I try running it without it... also breaks? And the mods I'm using NEED embeddium...

Please help... thanks!!
![image_2024-06-30_173713775](https://github.com/ThinkingStudios/textrues-embeddium-options/assets/135098588/da8b6368-99ec-40bc-8410-cdf7a462b7f8)
![image_2024-06-30_173728169](https://github.com/ThinkingStudios/textrues-embeddium-options/assets/135098588/7028c2d9-9b9f-418f-9914-3ead3941d851)

**Comment by TexBlock** [comment]
see #9

**Comment by hibleepbloop** [comment]
...that doesn't help me :( still doesn't run with AND without textrue. if there's something i'm missing, please tell me... do i have to update? do i have to downgrade??? is it just a problem with embeddium?

**Comment by TexBlock** [comment]
You need to modify META-INF/mods.toml inside embeddiumextras.jar by deleting the following

```toml
[[dependencies.${modid}]]
    modId="textrues_embeddium_options"
    mandatory=true
    versionRange="*"
    ordering="AFTER"
    side="CLIENT"
```
